Removing h4r_thermapp_camera source entry
It has been triggering every cycle due to using a tag not a branch. 

And it's also failing every cycle as well due to using an ssh submodule: 

```
h4r_thermapp_camera/ARCH_PARAM/amd64/UBUNTU_PARAM/trusty/label/devel/repo.rosinstall --catkin'
rosinstall operating on /tmp/test_repositories/src_repository from specifications in rosinstall files  /home/rosbuild/hudson/workspace/devel-indigo-h4r_thermapp_camera/ARCH_PARAM/amd64/UBUNTU_PARAM/trusty/label/devel/repo.rosinstall
(Over-)Writing /tmp/test_repositories/src_repository/.rosinstall
Cloning into '/tmp/test_repositories/src_repository/h4r_thermapp_camera'...
WARNING [vcstools] Command failed: 'git submodule update --init --recursive'
 run at: '/tmp/test_repositories/src_repository/h4r_thermapp_camera'
 errcode: 1:
Cloning into 'src/ThermAppCam'...
error: cannot run ssh: No such file or directory
fatal: unable to fork
Clone of 'git@github.com:Hacks4ROS-forks/ThermAppCam.git' into submodule path 'src/ThermAppCam' failed
[/vcstools]
[h4r_thermapp_camera] Fetching https://github.com/Hacks4ROS/h4r_thermapp_camera.git (version 0.0.1) to /tmp/test_repositories/src_repository/h4r_thermapp_camera
Submodule 'src/ThermAppCam' (git@github.com:Hacks4ROS-forks/ThermAppCam.git) registered for path 'src/ThermAppCam'

Exception caught during install: Error processing 'h4r_thermapp_camera' : [h4r_thermapp_camera] Checkout of https://github.com/Hacks4ROS/h4r_thermapp_camera.git version 0.0.1 into /tmp/test_repositories/src_repository/h4r_thermapp_camera failed.

ERROR in config: Error processing 'h4r_thermapp_camera' : [h4r_thermapp_camera] Checkout of https://github.com/Hacks4ROS/h4r_thermapp_camera.git version 0.0.1 into /tmp/test_repositories/src_repository/h4r_thermapp_camera failed.

/!\  Failed to execute command '['rosinstall', '/tmp/test_repositories/src_repository', '/home/rosbuild/hudson/workspace/devel-indigo-h4r_thermapp_camera/ARCH_PARAM/amd64/UBUNTU_PARAM/trusty/label/devel/repo.rosinstall', '--catkin']' with return code 1
Failed to execute command '['rosinstall', '/tmp/test_repositories/src_repository', '/home/rosbuild/hudson/workspace/devel-indigo-h4r_thermapp_camera/ARCH_PARAM/amd64/UBUNTU_PARAM/trusty/label/devel/repo.rosinstall', '--catkin']' with return code 1
+ echo ============================================================
```

Partially reverts #8549