Remove spinnaker_camera_driver
It's failing to build http://build.ros.org/view/Kbin_uX32/job/Kbin_uX32__spinnaker_camera_driver__ubuntu_xenial_i386__binary/
```
16:27:12 In file included from /tmp/binarydeb/ros-kinetic-spinnaker-camera-driver-0.1.3/include/spinnaker_camera_driver/camera.h:32:0,
16:27:12                  from /tmp/binarydeb/ros-kinetic-spinnaker-camera-driver-0.1.3/src/camera.cpp:25:
16:27:12 /tmp/binarydeb/ros-kinetic-spinnaker-camera-driver-0.1.3/include/spinnaker_camera_driver/set_property.h:29:23: fatal error: Spinnaker.h: No such file or directory
16:27:12 compilation terminated.
```

It looks like a missing dependency or include path.