[I] Remove temporarily.
Not entirely sure why CI failed, but I assume the version mismatch b/w the packages in the repo that the `moveit_full_pr2` is moved to.

This change removes `moveit_full_pr2` pkg from the entire ROS distro land, but it'll soon be added back when release for `moveit_pr2` is made.

https://travis-ci.org/ros/rosdistro/jobs/445789675
```
ERROR: test.test_build_caches.test_build_caches
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
  self.test(*self.arg)
    File "/home/travis/build/ros/rosdistro/test/test_build_caches.py", line 57, in test_build_caches
raise RuntimeError('\n'.join(errors))
RuntimeError: indigo: missing package.xml file for package "moveit_full_pr2"
-------------------- >> begin captured logging << --------------------
rosdistro: DEBUG: Load index from "file:///home/travis/build/ros/rosdistro/index.yaml"
rosdistro: DEBUG: Load cache from "http://repositories.ros.org/rosdistro_cache/indigo-cache.yaml.gz"
rosdistro: DEBUG: Load file from "file:///home/travis/build/ros/rosdistro/indigo/distribution.yaml"
rosdistro: DEBUG: Dropping release package XML cache for moveit_full_pr2
```